// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GoChat/config"
	"GoChat/internel/handler"
	"GoChat/internel/infrastructure/mq"
	"GoChat/internel/repository"
	"GoChat/internel/repository/cache"
	"GoChat/internel/service"
	"GoChat/pkg/db"

	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"gorm.io/gorm"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	client := providerRDB()
	redisCache := cache.NewRedisCache(client)
	db := providerDBMaster()
	convRepo := repository.NewConvRepo(db)
	seqFactoryService := service.NewSeqFactory(redisCache, convRepo)
	userRepo := repository.NewUserRepo(db)
	txManager := service.NewTxManager(db)
	userService := service.NewUserService(userRepo, redisCache, txManager)
	pushService := service.NewPushService(redisCache, userService)
	chatRepo := repository.NewChatRepo(db)
	config := providerConfig()
	ackProducer, err := providerKafkaACKProducer(config)
	if err != nil {
		return nil, err
	}
	ackConsumer, err := providerKafkaACKConsumer(config)
	if err != nil {
		return nil, err
	}
	chatService := service.NewChatService(seqFactoryService, pushService, chatRepo, convRepo, txManager, redisCache, ackProducer, ackConsumer)
	syncService := service.NewSyncService(redisCache, chatRepo, convRepo)
	chatHandler := handler.NewChatHandler(chatService, userService, syncService, pushService)
	userHandler := handler.NewUserHandler(userService)
	groupService := service.NewGroupService(convRepo, redisCache)
	groupHandler := handler.NewGroupHandler(groupService)
	app := &App{
		ChatHandler:  chatHandler,
		UserHandler:  userHandler,
		GroupHandler: groupHandler,
		ChatService:  chatService,
		PushService:  pushService,
		AckConsumer:  ackConsumer,
		AckProducer:  ackProducer,
	}
	return app, nil
}

// wire.go:

func providerConfig() *config.Config {
	return config.Cfg
}

func providerDBMaster() *gorm.DB {
	return db.GetDBS().Master
}

func providerRDB() *redis.Client {
	return db.GetRDS()
}

func providerKafkaACKProducer(cfg *config.Config) (*mq.AckProducer, error) {
	return mq.NewAckProducer(
		cfg.KafkaConfig.Brokers,
		&cfg.KafkaConfig.AckConfig,
	)
}

func providerKafkaACKConsumer(cfg *config.Config) (*mq.AckConsumer, error) {
	return mq.NewAckConsumer(
		cfg.KafkaConfig.Brokers,
		&cfg.KafkaConfig.AckConfig,
	)
}

// 定义 infrastructure 集合
var infrastructureSet = wire.NewSet(
	providerConfig,
	providerDBMaster,
	providerRDB,
	providerKafkaACKProducer,
	providerKafkaACKConsumer,
)

// 定义 repository 集合
var repositorySet = wire.NewSet(repository.NewUserRepo, repository.NewChatRepo, repository.NewConvRepo)

var cacheSet = wire.NewSet(cache.NewRedisCache)

// 定义 service 集合
var serviceSet = wire.NewSet(service.NewGroupService, wire.Bind(new(service.IGroupService), new(*service.GroupService)), service.NewUserService, wire.Bind(new(service.IUserService), new(*service.UserService)), service.NewChatService, wire.Bind(new(service.IChatService), new(*service.ChatService)), service.NewSyncService, wire.Bind(new(service.ISyncService), new(*service.SyncService)), service.NewPushService, wire.Bind(new(service.IPushService), new(*service.PushService)), service.NewTxManager, wire.Bind(new(service.ITxManager), new(*service.TxManager)), service.NewSeqFactory, wire.Bind(new(service.ISeqFactoryService), new(*service.SeqFactoryService)))

// 定义 handler 集合
var handlerSet = wire.NewSet(handler.NewUserHandler, handler.NewChatHandler, handler.NewGroupHandler)
